### ISSUE TITLE
include request points in profile

### ISSUE THREAD

**Issue by danduk82** [geoadmin/service-alti#42]
**as:** a user
**i want:** that profile returns also the points included in my original KML
**because:** if I click on a mountain peak, I want to see it in the profile

MUST have:
- [ ] inclusion of the request points in the returned polyline if an additional (non-default) parameter is added, such as `distinct_points=true`
- [ ] define a maximal value for points in input KML and return `400 Bad Request` or `413 Payload Too Large`, NB payload size can be tricked by reducing the decimal precision of points coordinates (which already happen on our current setup). But we might return `413 "payload to big, please use less than x points"`

CAN have:
- [ ] return `only` the altitudes corresponding to request points if an additional (non-default) parameter is added, such as `only_requested_points=true`

**Comment by danduk82** [comment]
@procrastinatio , can you modify [your old PR](https://github.com/geoadmin/service-alti/pull/34) to align with this issue?

**Comment by pakb** [comment]
superseded by https://github.com/geoadmin/service-alti/issues/64
