### ISSUE TITLE
increase resolution of output polyline to DEM resolution

### ISSUE THREAD

**Issue by danduk82** [geoadmin/service-alti#43]
**as:** a user
**i want:** the possibility to receive a very detailed profile, at the same resolution as the original DEM
**because:** I really want to see the exact altitude in profile when using `smoothing=0`

MUST have:
- [ ] **do not change the current default behavior**
- [ ] analysis of the tuple (number of points , requests per second) to decide the maximal length for max resolution
- [ ] add a `resolution` parameter so that the user can decide, such as `resolution=10m`. In this case the max length before switching to degraded resolution is updated accordingly.
- [ ] return `203 Non-Authoritative Information` if the max resolution cannot be used, and add a field `output-resolution` (in meters) in the output json, so that it can be displayed in mf-geoadmin3 profile

**Comment by pakb** [comment]
about adding a new field containing the resolution used for calculation to the JSON, this will mean changing our response structure (breaking change). Is that OK?

**Comment by pakb** [comment]
superseded by https://github.com/geoadmin/service-alti/issues/64
